version: '3.7'

services:
  app:
    build:
      context: .
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV:-development}
    ports:
      - "${APP_PORT:-80}:5000"
    volumes:
      - ".:/app/"
    networks:
      - face

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    ports:
      - ${ES_PORT:-9200}:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    networks:
      - face
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g
  kibana:
    mem_limit: 1g
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.6.2
    ports:
      - ${KIBANA_PORT:-5601}:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - face
    volumes:
      - kibana-data:/usr/share/kibana/data
    
networks:
  face:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
